# This is a basic workflow to help you get started with Actions

name: first workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get code
        uses: actions/checkout@v4
      - name: List files in the repo
        run: ls -al
      # install Python
      - name: Install Python
        uses: actions/setup-python@v5.6.0
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: 3.12
      - name: install package
        run: |
          # pip install -r requirements.txt
          pip install .[dev]
          pip list
      # Runs a single command using the runner's shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runner's shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build.
          echo test, and deploy your project.
      - name: Upload source code for testing
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: .  # include everything or just the needed directories

  test:
    runs-on: ubuntu-latest
    needs: build  # this ensures test runs after build completes

    steps:
      - name: Download source code from build
        uses: actions/download-artifact@v4
        with:
          name: source-code

      - name: Install Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.12

      - name: Install package
        run: |
          pip install .[dev]

      - name: Run unit tests
        run: |
          pytest ./calcpy/tests

  node-setup:
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.set-node.outputs.node-version }}

    steps:
      - name: Set up Node.js
        id: set-node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Show installed Node version
        run: echo "Node version is ${{ steps.set-node.outputs.node-version }}"
    
  use-node:
    runs-on: ubuntu-latest
    needs: node-setup

    steps:
      - name: Show node version from previous job
        run: echo "Node version from job: ${{ steps.set-node.outputs.node-version }}"